name: Gradle Build & UT

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-build.yml@gradle-publish-to-local
    with:
      flow-type: public
      java-version: '8'
